name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install Vulkan SDK
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.239-jammy.list https://packages.lunarg.com/vulkan/1.3.239/lunarg-vulkan-1.3.239-jammy.list
        sudo apt update
        sudo apt install vulkan-sdk
    
    - name: Install other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libglfw3 libglfw3-dev
    
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ../VulkenGrid
      working-directory: ${{ github.workspace }}
    
    - name: Build project
      run: |
        cd build
        make
      working-directory: ${{ github.workspace }}

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.239.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
        vulkan-use-cache: true
    
    - name: Setup CMake
      uses: lukka/get-cmake@latest
    
    - name: Add Vulkan SDK to PATH
      run: |
        echo "$env:VULKAN_SDK/Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Configure CMake
      run: |
        mkdir build -ErrorAction SilentlyContinue
        cd build
        cmake ..\VulkenGrid
      working-directory: ${{ github.workspace }}
    
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release
      working-directory: ${{ github.workspace }}